import AppKit

// MARK: - Clipboard Service

/// 剪贴板备份/写入/恢复服务
/// 职责：仅负责剪贴板操作，不涉及按键模拟或业务逻辑
final class ClipboardService {

    // NSPasteboard.org 标准标记类型
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private let pasteboard = NSPasteboard.general

    // MARK: - Backup Token

    struct BackupToken {
        let items: [[(NSPasteboard.PasteboardType, Data)]]
        let changeCount: Int
    }

    // MARK: - API

    /// 备份当前剪贴板内容，返回不透明 token
    func backup() -> BackupToken {
        let items = pasteboard.pasteboardItems?.compactMap { item -> [(NSPasteboard.PasteboardType, Data)]? in
            let data = item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            }
            return data.isEmpty ? nil : data
        } ?? []
        return BackupToken(items: items, changeCount: pasteboard.changeCount)
    }

    /// 将文本写入剪贴板（标记为不记录历史），返回写入后的 changeCount
    @discardableResult
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        pasteboard.setData(Data(), forType: Self.transientType)
        pasteboard.setData(Data(), forType: Self.autoGeneratedType)
        return pasteboard.changeCount
    }

    /// 恢复剪贴板到 token 中保存的内容
    func restore(_ token: BackupToken) {
        guard !token.items.isEmpty else { return }
        pasteboard.clearContents()
        let newItems = token.items.map { itemData -> NSPasteboardItem in
            let pbItem = NSPasteboardItem()
            for (type, data) in itemData { pbItem.setData(data, forType: type) }
            return pbItem
        }
        pasteboard.writeObjects(newItems)
    }

    /// 当前 changeCount
    var changeCount: Int { pasteboard.changeCount }
}
